#!/bin/sh

for a in bofa/ckg bofa/crc c1 citi; do
	tmp="$(mktemp)"
	find $a ! -name "$(printf "*\n*")" -iregex '.*\.[oq]fx' | sort > "$tmp"
	while IFS= read -r file
	do
		# echo \
		ledger-autosync \
			--unknown-account Expenses:Unknown \
			$([ "$1" ] && echo --rules "$1") \
			-a "$(cat $a/acct)" \
			$([ -e $a/fid ] && echo --fid $(cat $a/fid)) \
			"$file"
	done < "$tmp" | less -F
	rm "$tmp"
done 2>/dev/null

for a in fidelity pp pp/mc venmo; do
	tmp="$(mktemp)"
	if [ -s $a/csv ]; then
		$a/csv $a/*.csv > "$tmp"
	else
		cat $a/*.csv > "$tmp"
	fi
	# echo \
	ledger convert \
		--rich-data \
		--input-date-format "$(cat $a/date-format)" \
		--account "$([ -s $a/acct ] && cat $a/acct || echo assets:$a)" \
		$tmp
	rm "$tmp"
done
