#!/bin/sh

for a in bofa/ckg bofa/crc c1 citi/costco citi/custom fidelity/crc; do
	tmp="$(mktemp)"
	find $a ! -name "$(printf "*\n*")" -iregex '.*\.[oq]fx' | sort > "$tmp"
	while IFS= read -r file
	do
		# echo \
		ledger-autosync \
			--unknown-account Expenses:Unknown \
			-a "$(cat $a/acct)" \
			$([ -e $a/fid ] && echo --fid $(cat $a/fid)) \
			"$file" 2>/dev/null
	done < "$tmp" | less -F
	rm "$tmp"
done

for a in bofa/ckg bofa/crc fidelity fidelity/hsa pp pp/mc venmo; do
	tmp="$(mktemp)"
	if [ -s $a/csv ]; then
		$a/csv $a/*.csv > "$tmp"
	else
		cat $a/*.csv > "$tmp"
	fi
	# echo \
	ledger convert \
		--rich-data \
		--input-date-format "$(cat $a/date-format)" \
		--account "$(
			if [ -s $a/acct ]; then cat $a/acct
			else echo assets:$a | tr / :; fi)" \
		$tmp
	rm "$tmp"
done
