#!/bin/sh

for f in "$@"; do
	# Skip directories
	[ -d "$f" ] && continue

	# Reformat date from filename
	date_str=$(basename "${f%.*}" | awk -F_ 'BEGIN {
		m["Jan"]="01"; m["Feb"]="02"; m["Mar"]="03";
		m["Apr"]="04"; m["May"]="05"; m["Jun"]="06";
		m["Jul"]="07"; m["Aug"]="08"; m["Sep"]="09";
		m["Oct"]="10"; m["Nov"]="11"; m["Dec"]="12";
	}
	NF == 3 { print $3 "-" m[$2] }
	NF == 4 { print $4 "-" m[$2] "--" m[$3] }
	NF == 5 { print $3 "-" m[$2] "--" $5 "-" m[$4] }
	')

	# Skip if no valid date
	[ -z "$date_str" ] && continue

	# echo \
	mv -n "$f" "$(dirname "$f")/$date_str.csv"
done

