#!/bin/sh

echo "Date,Description,debit,Running Bal."

awk 'FNR > 8 {print}' "$@" | sed -E 's/("[^",]+")",/"\1"",/' | awk --csv '{
	$3 = "$" $3
	for (i = 1; i <= NF; i++) {
		f = $i
		gsub(/"/, "\"\"", f)
		printf "%s\"%s\"", (i==1?"":","), f
	}
	printf "\n"
}
'
