#!/bin/sh

awk -v OFS=',' 'BEGIN {
	print \
	"desc",
	"ID",                          # ID
	"Datetime",                    # Datetime
	"Type",                        # Type
	"Status",                      # Status
	"Note",                        # Note
	"From",                        # From
	"To",                          # To
	"debit",                       # Amount (total)
	"",                            # Amount (tip)
	"",                            # Amount (tax)
	"",                            # Amount (fee)
	"Tax Rate",                    # Tax Rate
	"Tax Exempt",                  # Tax Exempt
	"Funding Source",              # Funding Source
	"Destination",                 # Destination
	"Beginning Balance",           # Beginning Balance
	"Ending Balance",              # Ending Balance
	"Statement Period Venmo Fees", # Statement Period Venmo Fees
	"Terminal Location",           # Terminal Location
	"",                            # Year to Date Venmo Fees
	"Disclaimer"                   # Disclaimer
}'

awk="$(command -v nawk || command -v gawk || echo awk)"

for file in "$@"; do
	# Skip dirs or empty files
	{ [ -d "$file" ] || [ ! -s "$file" ]; } && continue

	eval "$awk" --csv -v OFS='","' 'NR > 4 && NR < '$(($(wc -l < "$file") - 26))' {
		if ($9 ~ "-") {
			$1 = $8 ? $8 : $16
		} else {
			$1 = $7 ? $7 : $15
		}
		sub(/T.*/, "", $3)
		sub("+", "", $9)
		print "\"" $0 "\""
	}' "$file"
done
